### PR TITLE
92/CI Base RDF Enhancments

### PR DESCRIPTION
**Pull request by MichaelMcAleer**
This pull request makes some changes to the base CI function to create RDFGs to account for fail scenarios and try again with cleanup at the end.

The minimum Unisphere version has also been updated to reflect the GA version number of Unisphere for PowerMax (9.2.0.1).

### CODE REVIEW

**Review by odonos12 — APPROVED** [review]
Looks fine overall. Just wondering what kind of blocks are alleviated by the retries? Symmetrix lock issues?

**Comment by MichaelMcAleer** [comment]
Yeah primarily symm locks but resilient against things like timeouts and connection drops.

**Comment by MichaelMcAleer** [comment]
> Looks fine overall. Just wondering what kind of blocks are alleviated by the retries? Symmetrix lock issues?

Yeah primarily symm locks but resilient against things like timeouts and connection drops.

**Review by rawstorage — APPROVED** [review]

**Review by helenwalsh — APPROVED** [review]
Approving pending clean CI.

**Comment by MichaelMcAleer** [comment]
Clean CI achieved overnight, merging.

**Pull request merged**
