### PR TITLE
feat: add possibility of configuring proxies

### LINKED ISSUE #153: Support for proxies in requests
It would be nice to be able to configure proxies for the HTTP requests. 

Using https://requests.readthedocs.io/en/latest/user/advanced/?highlight=proxies#proxies it could be introduced on the `requests.session` object https://github.com/dell/PyU4V/blob/master/PyU4V/rest_requests.py#L69

### PR DESCRIPTION
**Pull request by arthurzenika**
closes #153

### CODE REVIEW

**Comment by rawstorage** [comment]
Thanks for this Contribution arthur, we will need to create a CI test for this pull request and run through our CI pipeline to make sure nothing gets broken before merge, I have some additional changes in the pipeline and will see if this can be merged into PyU4V 10.0 also.  Do you need this fix at 9.2 or are you able to upgrade and use in 10.0.x version?

**Comment by rawstorage** [comment]
no this is fine, I can port if forward once I've had chance to run CI on it.

**Comment by arthurzenika** [comment]
Yes our use is on the 9.2 branch. I'm not sure I understand your comment about the CI, do you mean I should add a test ? or just that have to wait for the CI to run on your infrastructure ?

**Comment by rawstorage** [comment]
CI is our continuous integration, we run pytest with CI and Unit tests on all functions to make sure we don't break anything with additions and changing versions.  I can add this before I test and do a release.

**Comment by rawstorage** [comment]
Arthur,  this has been updated in 10.0.0.18, the 9.2 branch can not be updated, if possible can you update to version 10.x Unipshere version 10 will also be required.

**Comment by arthurzenika** [comment]
@rawstorage for my use case I cannot use the 10.x branch since I'm querying a 9.x vsphere installation. Any chance of having a bugfix release on the 9.2 branch ?

**Comment by rawstorage** [comment]
Arthur,
I'll bring this one up with the team in the new year, it's technically not a bugfix but a feature request which we usually only bring to existing release.  If you can pull into https://github.com/dell/PyU4V/tree/stable/9.2 branch I can try to get a release at this code, no promises yet..

In the meantime  you can build the package using setup.py  from your on branch and install with the .whl file, this may give you some relief until we can give a definitive answer on whether or not we can backport.

Paul Martin
Senior Principal Engineering Technologist
DellEMC | Enterprise Software and Storage - PowerMax and VMAX
Cell +35387 696 0621
Timezone GMT

Follow me on Twitter @rawstorage
Blog https://rawstorage.wordpress.com/

WhitePapers - https://infohub.delltechnologies.com/t/storage/

**Comment by arthurzenika** [comment]
@rawstorage thanks for taking the time to look at this and pushing it to the team. Here is the PR : https://github.com/dell/PyU4V/pull/160

**Pull request closed without merging**
