### PR TITLE
feat: add possibility of configuring proxies in 9.2 branch

### PR DESCRIPTION
**Pull request by arthurzenika**
Closes #154 for 9.2 branch (useful for clients using 9.x pmax)

### CODE REVIEW

**Comment by arthurzenika** [comment]
@rawstorage Hi, any news from the team about integrating this in the 9.x branch ?

**Comment by rawstorage** [comment]
I will likely implement before the end of the month/early February teams just getting ramped up again

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rawstorage** [comment]
Closed in Pull Request #161 created my own pull as version needed to be updated, hopefully push to PyPi this week pending review and CI test

**Comment by arthurzenika** [comment]
Great news ! Looking forward to the release (and this will avoid us some complicated setup to package/publish internally the feature in a fork!)

**Comment by rawstorage** [comment]
Arthur,
Version 9.2.1.7 is available with this change.

pip install PyU4V==9.2.1.7

Paul Martin
Senior Principal Engineering Technologist
DellEMC | Enterprise Software and Storage - PowerMax and VMAX
Cell +35387 696 0621
Timezone GMT

Follow me on Twitter @rawstorage
Blog https://rawstorage.wordpress.com/

WhitePapers - https://infohub.delltechnologies.com/t/storage/

**Comment by rawstorage** [comment]
fix is release 9.2.1.7 available on PyPi

**Pull request closed without merging**
