### PR TITLE
Added Compression Functions from 83 URLS

### PR DESCRIPTION
**Pull request by rawstorage**

### CODE REVIEW

**Comment by rawstorage** [comment]
Added Compression functions

**Comment by rawstorage** [comment]
corrected payload on compressed storage group creation

**Comment by rawstorage** [comment]
apologies, still figuring this GiT out, should be good to merge now, two new functions

**Review by ciarams87 — APPROVED** [review]

**Comment by rawstorage** [comment]
Accidentally hoaxed into the root aging.  Latest in PyU4V should have 2 new function to check headroom and admissibility.  Will add scripts to check admissibility soon

**Pull request closed without merging**
