### PR TITLE
Adding an option into create_storage_group for creating thick volumes

### PR DESCRIPTION
**Pull request by jbrt**
Hello,

I've added a little option into create_storage_group because, sometimes, we have to create thick volumes instead of thin (boot on SAN volumes for instance).

Best regards

### CODE REVIEW

**Comment by ghost** [comment]
Hey Julien,

I have no problem merging this pull request into the master branch, in order to do so though unit tests will need to be created for the change and all existing unit tests running clean after the change.  Update this request with the unit tests and copy/paste the results and ill get it merged.

Thanks!

**Comment by rawstorage** [comment]
Julien, can you update the testing file for this change per the request. once this is done we will merge with master

**Comment by jbrt** [comment]
Hi Paul,
Yes, I did'nt forget. I'll do this as soon as go back to work thrusday.
Regards

**Comment by jbrt** [comment]
Hello,
I've updated this PR with the relevant unit test.

**Comment by rawstorage** [comment]
Merged after running unit test, merged from local copy as conflicts on this one.

**Pull request closed without merging**
