### PR TITLE
Header Typo

### PR DESCRIPTION
**Pull request by rawstorage**
fix for typo in header application_type should have been application-type.  Header is ignored if incorrect.  Incremented version to 3.1.5

### CODE REVIEW

**Review by helenwalsh — APPROVED** [review]
looks goods.  I presume its not case sensitive.  See Application-Type in some places.  However, I don't think it matters

**Review by MichaelMcAleer — CHANGES_REQUESTED** [review]
Any changes require an associated unit-test, looks good otherwise

**Review by MichaelMcAleer — APPROVED** [review]
Looks good to me, feel free to merge now with +2 and get the pypi updated, thanks Paul

**Comment by rawstorage** [comment]
I'll add same change into 9.1 also.

**Comment by MichaelMcAleer** [comment]
> I'll add same change into 9.1 also.

Leave it off, ill do it as part of the work on improving exceptions and want to do the user-agent part also

**Pull request merged**
