### PR TITLE
add support to provide metro r2 dr rdf group

### PR DESCRIPTION
**Pull request by SerDroide**
Add support to provide metro r2 dr rdf group when converting to a metro dr environment

### CODE REVIEW

**Review by rawstorage — COMMENTED** [review]
These look good but will need to update CI Tests and Unit Tests, I will run locally when I get a chance and merge with version increment.

**Review by rawstorage — COMMENTED** [review]
Noted this change is for 10.1 version,  I can only bring enhancements into 10.2 or higher.  If you want for me to merge to the latest version let me know.

**Comment by SerDroide** [comment]
yes, please, merge into 10.2

**Comment by rawstorage** [comment]
Sergio, I have added this into a separate branch and run CI tests on it.    I will merge my branch as I had some other work to go in.  Thanks so much for contributing to the project.

**Pull request closed without merging**
